    catch(...){
        cout << "Unknown error" << endl;
    }